name: Win-Build

on: [push, pull_request]

jobs:
    build-windows:
        runs-on: windows-latest
        env:
            VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
            MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1
                  submodules: true

            - name: Generating Project Files
              shell: cmd
              run: |
                  CMakeLists.txt

            - name: Building Trigger
              shell: cmd
              run: '"%MSBUILD_PATH%\MSBuild.exe" build/ALL_BUILD.vcxproj /p:Platform=x64 /p:Configuration=Release'

            - name: Running Tests
              shell: cmd
              run: '"%MSBUILD_PATH%\MSBuild.exe" build/test/triggertest.vcxproj /p:Platform=x64 /p:Configuration=Release'
